### ISSUE TITLE
Swift Version

### ISSUE THREAD

**Issue by cliftonlabrum** [astrokin/PieChart#1]
This looks really nice. Have you considered rewriting it in Swift?

I also thought a simpler example would be good where you just specify the number of segments and the color for each in code (and not use the sliders).

Thank you!

**Comment by astrokin** [comment]
Hello.
Thanks for the interest to my project.
Yes, i had a plan to write it in swift too, but now you can use objc code in swift classes.
Sliders it's just an example, you should use delegate methods in your view class. 
Have a good coding!
Ask if any question.
