### ISSUE TITLE
Upload the library to CocoaPods

### ISSUE THREAD

**Issue by reden87** [astrokin/PieChart#2]
Would be a nice feature :)

**Comment by astrokin** [comment]
@reden87 thanks for your feedback. I have plans for that. Will do it shortly.

**Comment by astrokin** [comment]
🎉  Congrats

 🚀  JustPieChart (0.1.0) successfully published
 📅  October 27th, 23:03
 🌎  https://cocoapods.org/pods/JustPieChart
 👍  Tell your friends!
